
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using POS.Application.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection.Metadata;
using System.Text;
using POS.Application.Interfaces;



namespace POS.Application.Services
{
    public class PdfInvoiceService : IPdfInvoiceService
    {
        public byte[] GenerateInvoicePdf(OrderDetailViewModel order)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            return QuestPDF.Fluent.Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A5);
                    page.Margin(1.5f, Unit.Centimetre);
                    page.DefaultTextStyle(x => x.FontSize(10));

                    page.Header().Element(ComposeHeader);
                    page.Content().Element(c => ComposeContent(c, order));
                    page.Footer().AlignCenter().Text(t =>
                    {
                        t.Span("Thank you! Invoice generated by POS System · Page ");
                        t.CurrentPageNumber();
                        t.Span(" of ");
                        t.TotalPages();
                    });
                });
            }).GeneratePdf();

            void ComposeHeader(QuestPDF.Infrastructure.IContainer c)
            {
                c.Row(row =>
                {
                    row.RelativeItem().Column(col =>
                    {
                        col.Item().Text(order.BranchName).Bold().FontSize(16);
                        col.Item().Text(order.BranchAddress).FontColor(Colors.Grey.Darken2);
                        col.Item().Text($"Tel: {order.BranchPhone}").FontColor(Colors.Grey.Darken2);
                    });
                    row.ConstantItem(100).AlignRight().Column(col =>
                    {
                        col.Item().Text("INVOICE").Bold().FontSize(14).FontColor(Colors.Blue.Darken3);
                        col.Item().Text($"#{order.InvoiceNumber}").Bold();
                        col.Item().Text(order.CreatedAt.ToString("dd MMM yyyy")).FontColor(Colors.Grey.Darken2);
                    });
                });
            }

            void ComposeContent(QuestPDF.Infrastructure.IContainer c, OrderDetailViewModel order)
            {
                c.Column(col =>
                {
                    col.Spacing(8);
                    col.Item().LineHorizontal(0.5f);

                    // Customer info
                    if (!string.IsNullOrEmpty(order.CustomerName))
                    {
                        col.Item().Text($"Customer: {order.CustomerName}").SemiBold();
                        if (!string.IsNullOrEmpty(order.CustomerPhone))
                            col.Item().Text($"Phone: {order.CustomerPhone}");
                    }

                    // Items table
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(cols =>
                        {
                            cols.RelativeColumn(4);
                            cols.RelativeColumn(1);
                            cols.RelativeColumn(2);
                            cols.RelativeColumn(2);
                        });

                        // Header
                        table.Header(header =>
                        {
                            foreach (var h in new[] { "Product", "Qty", "Unit Price", "Total" })
                                header.Cell().Background(Colors.Blue.Lighten4)
                                      .Padding(4).Text(h).Bold();
                        });

                        // Rows
                        foreach (var item in order.Items)
                        {
                            table.Cell().Padding(4).Text(item.ProductName);
                            table.Cell().Padding(4).AlignCenter().Text(item.Quantity.ToString());
                            table.Cell().Padding(4).AlignRight().Text($"৳{item.UnitPrice:N2}");
                            table.Cell().Padding(4).AlignRight().Text($"৳{item.LineTotal:N2}");
                        }
                    });

                    // Totals
                    col.Item().AlignRight().Column(totals =>
                    {
                        totals.Item().Row(r =>
                        {
                            r.RelativeItem().Text("Subtotal:").SemiBold();
                            r.ConstantItem(80).AlignRight().Text($"৳{order.SubTotal:N2}");
                        });
                        if (order.DiscountAmount > 0)
                            totals.Item().Row(r =>
                            {
                                r.RelativeItem().Text("Discount:").FontColor(Colors.Red.Medium);
                                r.ConstantItem(80).AlignRight().Text($"-৳{order.DiscountAmount:N2}").FontColor(Colors.Red.Medium);
                            });
                        if (order.TaxAmount > 0)
                            totals.Item().Row(r =>
                            {
                                r.RelativeItem().Text("Tax/VAT:");
                                r.ConstantItem(80).AlignRight().Text($"৳{order.TaxAmount:N2}");
                            });

                        totals.Item().LineHorizontal(0.5f);
                        totals.Item().Row(r =>
                        {
                            r.RelativeItem().Text("TOTAL:").Bold().FontSize(13);
                            r.ConstantItem(80).AlignRight().Text($"৳{order.TotalAmount:N2}").Bold().FontSize(13);
                        });
                    });

                    // Payment
                    col.Item().LineHorizontal(0.5f);
                    foreach (var p in order.Payments)
                        col.Item().Row(r =>
                        {
                            r.RelativeItem().Text($"Paid ({p.Method}):").SemiBold();
                            r.ConstantItem(80).AlignRight().Text($"৳{p.Amount:N2}");
                        });
                });
            }
        }
    }
}
